In [2]:
import numpy as np
import pandas as pd

# 1. Create array from 0 to 5 and print data type
arr1 = np.arange(6)
print("Array 1:", arr1)
print("Data type:", arr1.dtype)

# 2. Check if data type is float64
arr2 = np.array([1.0, 2.0, 3.0])
is_float64 = arr2.dtype == np.float64
print("\nIs arr2 float64?:", is_float64)

# 3. Create complex128 array
arr3 = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("\nComplex128 Array:", arr3)

# 4. Convert integer array to float32
arr4 = np.array([1, 2, 3, 4])
arr4_float32 = arr4.astype(np.float32)
print("\nConverted to float32:", arr4_float32)

# 5. Convert float64 array to float32
arr5 = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr5_float32 = arr5.astype(np.float32)
print("\nReduced precision float32:", arr5_float32)

# 6. Function to return shape, size, dtype
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

# Example usage
example_arr = np.array([[1, 2], [3, 4]])
print("\nArray attributes (shape, size, dtype):", array_attributes(example_arr))

# 7. Function to return dimensionality
def array_dimension(arr):
    return arr.ndim

# Example usage
print("\nArray dimension:", array_dimension(example_arr))

# 8. Function to return item size and total size
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

# Example usage
print("\nItem size & total size (bytes):", item_size_info(example_arr))

# 9. Function to return strides
def array_strides(arr):
    return arr.strides

# Example usage
print("\nArray strides:", array_strides(example_arr))

# 10. Return shape and strides of the array
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
# Example
arr10 = np.array([[1, 2], [3, 4]])
print("10. Shape & Strides:", shape_stride_relationship(arr10))



Array 1: [0 1 2 3 4 5]
Data type: int32

Is arr2 float64?: True

Complex128 Array: [1.+2.j 3.+4.j 5.+6.j]

Converted to float32: [1. 2. 3. 4.]

Reduced precision float32: [1.1 2.2 3.3]

Array attributes (shape, size, dtype): ((2, 2), 4, dtype('int32'))

Array dimension: 2

Item size & total size (bytes): (4, 16)

Array strides: (8, 4)
10. Shape & Strides: ((2, 2), (8, 4))


In [3]:
# 11. Create array of n zeros
def create_zeros_array(n):
    return np.zeros(n)

print("\n11. Zeros Array:", create_zeros_array(5))

# 12. Create 2D array of ones (rows x cols)
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print("\n12. Ones Matrix:\n", create_ones_matrix(2, 3))

# 13. Create ranged NumPy array
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print("\n13. Range Array:", generate_range_array(1, 10, 2))

# 14. Equally spaced values using linspace
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print("\n14. Linear Space:", generate_linear_space(0, 1, 5))

# 15. Create identity matrix using eye
def create_identity_matrix(n):
    return np.eye(n)

print("\n15. Identity Matrix:\n", create_identity_matrix(4))

# 16. Convert list to NumPy array
def list_to_array(py_list):
    return np.array(py_list)

print("\n16. List to Array:", list_to_array([1, 2, 3, 4]))

# 17. Create view of a NumPy array
arr17 = np.array([10, 20, 30, 40])
arr17_view = arr17.view()
print("\n17. Original:", arr17)
print("View:", arr17_view)



11. Zeros Array: [0. 0. 0. 0. 0.]

12. Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]

13. Range Array: [1 3 5 7 9]

14. Linear Space: [0.   0.25 0.5  0.75 1.  ]

15. Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

16. List to Array: [1 2 3 4]

17. Original: [10 20 30 40]
View: [10 20 30 40]


In [4]:
# 18. Concatenate two arrays along a given axis
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr18_a = np.array([[1, 2], [3, 4]])
arr18_b = np.array([[5, 6], [7, 8]])
print("\n18. Concatenated Array:\n", concatenate_arrays(arr18_a, arr18_b, axis=0))

# 19. Concatenate arrays of different shapes horizontally
def horizontal_concat_diff_shapes(arr1, arr2):
    return np.concatenate((arr1, arr2), axis=1)

arr19_a = np.array([[1], [2]])
arr19_b = np.array([[3, 4], [5, 6]])
print("\n19. Horizontal Concatenation:\n", horizontal_concat_diff_shapes(arr19_a, arr19_b))

# 20. Vertically stack arrays from list
def vertical_stack_arrays(array_list):
    return np.vstack(array_list)

arr20_1 = np.array([1, 2, 3])
arr20_2 = np.array([4, 5, 6])
arr20_3 = np.array([7, 8, 9])
print("\n20. Vertically Stacked Arrays:\n", vertical_stack_arrays([arr20_1, arr20_2, arr20_3]))


18. Concatenated Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

19. Horizontal Concatenation:
 [[1 3 4]
 [2 5 6]]

20. Vertically Stacked Arrays:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy as np

# 21. Generate array of integers within a range (inclusive) with step
def generate_integer_range(start, stop, step):
    return np.arange(start, stop + 1, step)

# Example
print("21. Integer Range Array:", generate_integer_range(1, 10, 2))

# 22. Generate 10 equally spaced values between 0 and 1
def generate_equal_spaced_0_to_1():
    return np.linspace(0, 1, 10)

# Example
print("\n22. 10 Equally Spaced Values (0 to 1):", generate_equal_spaced_0_to_1())

# 23. Create 5 logarithmically spaced values between 1 and 1000
def generate_log_spaced_values():
    return np.logspace(np.log10(1), np.log10(1000), 5)

# Example
print("\n23. Logarithmically Spaced Values (1 to 1000):", generate_log_spaced_values())


21. Integer Range Array: [1 3 5 7 9]

22. 10 Equally Spaced Values (0 to 1): [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

23. Logarithmically Spaced Values (1 to 1000): [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [6]:
#24. Create random integers between 1 and 100
data = np.random.randint(1, 101, size=(5, 3))  # 5 rows, 3 columns

# Create DataFrame
df = pd.DataFrame(data, columns=['A', 'B', 'C'])

# Print DataFrame
print("DataFrame:\n", df)

# 25.Example DataFrame with some negative values
df2 = pd.DataFrame({
    'A': [5, -3, 8, -1, 2],
    'B': [-7, 6, -2, 9, -5]
})

print("\nOriginal DataFrame:\n", df2)

# Replace negative values in column 'A' with 0
df2['A'] = np.where(df2['A'] < 0, 0, df2['A'])

# Print updated DataFrame
print("\nUpdated DataFrame (negatives in 'A' replaced with 0):\n", df2)

DataFrame:
     A   B   C
0  64   4  52
1  31  82  72
2  25  32  60
3  12  88  58
4  20  77  75

Original DataFrame:
    A  B
0  5 -7
1 -3  6
2  8 -2
3 -1  9
4  2 -5

Updated DataFrame (negatives in 'A' replaced with 0):
    A  B
0  5 -7
1  0  6
2  8 -2
3  0  9
4  2 -5


In [7]:

# 26. Access the 3rd element from the given NumPy array
arr = np.array([10, 20, 30, 40, 50])
print(" 3rd element:", arr[2])  # Index 2

# 27. Retrieve the element at index (1, 2) from a 2D array
arr = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("\n27. Element at (1, 2):", arr[1, 2])

# 28. Extract elements greater than 5 using boolean indexing
arr28 = np.array([1, 6, 3, 8, 5, 9, 2])
greater_than_5 = arr28[arr28 > 5]
print("\n28. Elements > 5:", greater_than_5)

# 29. Slice elements from index 2 to 5 (inclusive)
arr29 = np.array([10, 20, 30, 40, 50, 60, 70])
slice_2_to_5 = arr29[2:6]  # index 2 to index 5 inclusive → arr[2:6]
print("\n29. Slice index 2 to 5:", slice_2_to_5)

# 30. Slice sub-array [[2, 3], [5, 6]] from a 2D array
arr30 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
sub_array_30 = arr30[0:2, 1:3]
print("\n30. Sub-array [[2, 3], [5, 6]]:\n", sub_array_30)

 3rd element: 30

27. Element at (1, 2): 6

28. Elements > 5: [6 8 9]

29. Slice index 2 to 5: [30 40 50 60]

30. Sub-array [[2, 3], [5, 6]]:
 [[2 3]
 [5 6]]


In [8]:
# 31. Extract elements based on indices from a 2D array
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])
rows_to_extract = [0, 2]
extracted_rows = array_2d[rows_to_extract, :]
print("31. Extracted rows:\n", extracted_rows)

# 32. Filter elements greater than a threshold using boolean indexing
array_1d = np.array([5, 12, 7, 18, 3, 25])
threshold = 10
filtered_elements = array_1d[array_1d > threshold]
print("\n32. Elements > 10:", filtered_elements)

# 33. Extract specific elements from a 3D array using separate index arrays
array_3d = np.arange(27).reshape(3, 3, 3)
i = np.array([0, 1, 2])
j = np.array([0, 1, 2])
k = np.array([0, 1, 2])
specific_elements = array_3d[i, j, k]
print("\n33. Specific elements from 3D array:", specific_elements)

# 34. Return elements satisfying two boolean conditions
array_conditions = np.array([5, 12, 7, 18, 3, 25, 15])
result = array_conditions[(array_conditions > 10) & (array_conditions < 20)]
print("\n34. Elements >10 and <20:", result)

# 35. Extract elements from a 2D array using separate row and column index arrays
array_2d_example = np.array([[11, 12, 13],
                             [21, 22, 23],
                             [31, 32, 33]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
extracted_elements = array_2d_example[row_indices, col_indices]
print("\n35. Elements using row & col indices:", extracted_elements)


31. Extracted rows:
 [[10 20 30]
 [70 80 90]]

32. Elements > 10: [12 18 25]

33. Specific elements from 3D array: [ 0 13 26]

34. Elements >10 and <20: [12 18 15]

35. Elements using row & col indices: [12 23 31]


In [9]:
# 36. Add scalar 5 to every element of an array using broadcasting.
arr36 = np.array([[1, 2, 3], [4, 5, 6]])
result36 = arr36 + 5
print("36. Add scalar 5:\n", result36)

# 37. Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array.
arr37 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])  # shape (3,4)
row_multiplier = np.array([[1], [2], [3]])  # shape (3,1)
result37 = arr37 * row_multiplier  # broadcasting multiplies each row
print("\n37. Multiply each row by scalar:\n", result37)

# 38. Add a (1, 4) array to every row of a (4, 3) array using broadcasting.
arr38 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])  # shape (4,3)
to_add = np.array([[10, 20, 30, 40]])  # shape (1,4)
result38 = arr38 + to_add.T
print("\n38. Add (1,4) to (4,3) rows:\n", result38)

# 39. Add two arrays of shapes (3, 1) and (1, 3) using broadcasting.
arr39_1 = np.array([[1], [2], [3]])  # shape (3,1)
arr39_2 = np.array([[10, 20, 30]])  # shape (1,3)
result39 = arr39_1 + arr39_2  # Result shape will be (3,3)
print("\n39. Add (3,1) and (1,3):\n", result39)

# 40. Handle shape incompatibility during multiplication between (2, 3) and (2, 2) array.
arr40_a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2,3)
arr40_b = np.array([[7, 8], [9, 10]])      # shape (2,2)
try:
    result40 = arr40_a * arr40_b
except ValueError as e:
    print("\n40. Error due to incompatible shapes:\n", e)
arr40_b_fixed = np.array([[2], [3]])  # shape (2,1)
result40_fixed = arr40_a * arr40_b_fixed  # broadcasting will work
print("\n40. Fixed multiplication using broadcasting:\n", result40_fixed)

36. Add scalar 5:
 [[ 6  7  8]
 [ 9 10 11]]

37. Multiply each row by scalar:
 [[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]

38. Add (1,4) to (4,3) rows:
 [[11 12 13]
 [24 25 26]
 [37 38 39]
 [50 51 52]]

39. Add (3,1) and (1,3):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]

40. Error due to incompatible shapes:
 operands could not be broadcast together with shapes (2,3) (2,2) 

40. Fixed multiplication using broadcasting:
 [[ 2  4  6]
 [12 15 18]]


In [10]:
arr = np.array([[2, 4, 6],
                [1, 3, 5],
                [7, 9, 11]])

# 41. Calculate column-wise mean of a 2D array.
col_mean = np.mean(arr, axis=0)
print("41. Column-wise mean:\n", col_mean)

# 42. Find maximum value in each row.
row_max = np.max(arr, axis=1)
print("\n42. Maximum value in each row:\n", row_max)

# 43. Find indices of maximum values in each column.
col_max_indices = np.argmax(arr, axis=0)
print("\n43. Indices of max values in each column:\n", col_max_indices)

# 44. Apply a custom function to compute moving sum along rows (window=2).
def moving_sum_rowwise(x):
    return np.array([np.convolve(row, np.ones(2, dtype=int), 'valid') for row in x])

row_moving_sum = moving_sum_rowwise(arr)
print("\n44. Moving sum along rows (window=2):\n", row_moving_sum)

# 45. Check if all elements in each column are even.
is_even = arr % 2 == 0
col_all_even = np.all(is_even, axis=0)
print("\n45. Are all elements in each column even?\n", col_all_even)

41. Column-wise mean:
 [3.33333333 5.33333333 7.33333333]

42. Maximum value in each row:
 [ 6  5 11]

43. Indices of max values in each column:
 [2 2 2]

44. Moving sum along rows (window=2):
 [[ 6 10]
 [ 4  8]
 [16 20]]

45. Are all elements in each column even?
 [False False False]


In [ ]:

arr1 = np.array([[1, 2], [3, 4], [5, 6]])  # shape (3,2)
arr2 = np.array([[10, 20], [30, 40], [50, 60]])  # shape (3,2)

# 46. Reshape a given array into dimensions m x n.
reshaped = arr1.reshape(2, 3)  # from (3,2) to (2,3)
print("46. Reshaped array (2x3):\n", reshaped)

# 47. Return a flattened version of a given matrix.
flattened = arr1.flatten()
print("\n47. Flattened array:\n", flattened)

# 48. Concatenate two arrays along a specified axis.
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
print("\n48. Concatenated along axis=0:\n", concat_axis0)

# Along axis=1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
print("\n48. Concatenated along axis=1:\n", concat_axis1)

# 49. Split an array into sub-arrays along a specified axis.
split_axis1 = np.hsplit(arr1, 2)
print("\n49. Split along axis=1 (columns):")
for i, part in enumerate(split_axis1):
    print(f" Part {i+1}:\n", part)


split_axis0 = np.vsplit(arr1, 3)
print("\n49. Split along axis=0 (rows):")
for i, part in enumerate(split_axis0):
    print(f" Part {i+1}:\n", part)

# 50. Insert and delete elements at specified indices from an array
arr3 = np.array([10, 20, 30, 40, 50])

inserted = np.insert(arr3, 2, 99)
print("\n50. Insert 99 at index 2:\n", inserted)

deleted = np.delete(arr3, 3)
print("50. Delete element at index 3:\n", deleted)

In [11]:
arr1 = np.array([[2, 4, 6],
                 [8, 10, 12]])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# 51. Perform element-wise addition between two arrays.
add_result = arr1 + arr2
print("51. Element-wise addition:\n", add_result)

# 52. Perform element-wise subtraction: subtract arr2 from arr1.
sub_result = arr1 - arr2
print("\n52. Element-wise subtraction (arr1 - arr2):\n", sub_result)

# 53. Perform element-wise multiplication.
mul_result = arr1 * arr2
print("\n53. Element-wise multiplication:\n", mul_result)

# 54. Divide elements of arr1 by arr2 element-wise.
div_result = arr1 / arr2
print("\n54. Element-wise division (arr1 / arr2):\n", div_result)

# 55. Perform element-wise exponentiation: arr1 ** arr2.
exp_result = arr1 ** arr2
print("\n55. Element-wise exponentiation (arr1 ** arr2):\n", exp_result)

51. Element-wise addition:
 [[ 3  6  9]
 [12 15 18]]

52. Element-wise subtraction (arr1 - arr2):
 [[1 2 3]
 [4 5 6]]

53. Element-wise multiplication:
 [[ 2  8 18]
 [32 50 72]]

54. Element-wise division (arr1 / arr2):
 [[2. 2. 2.]
 [2. 2. 2.]]

55. Element-wise exponentiation (arr1 ** arr2):
 [[      2      16     216]
 [   4096  100000 2985984]]


In [13]:
str_arr = np.array(['Hello World', 'NumPy Is FUN', 'Data Science'])

# 56. Count occurrences of a substring in a string array.
substring = 'o'
count_occurrences = np.char.count(str_arr, substring)
print("56. Occurrences of substring 'o':\n", count_occurrences)

# 57. Extract uppercase characters from a string array.
def extract_uppercase(arr):
    return np.array([''.join([ch for ch in s if ch.isupper()]) for s in arr])

uppercase_chars = extract_uppercase(str_arr)
print("\n57. Uppercase characters in each string:\n", uppercase_chars)
# 58. Replace substring occurrences with another string in a string array.
replaced_arr = np.char.replace(str_arr, ' ', '_')
print("58. Replace spaces with underscores:\n", replaced_arr)

# 59. Concatenate strings in a NumPy array element-wise.
concatenated_arr = np.char.add(str_arr, '!!!')
print("\n59. Concatenate '!!!' to each string:\n", concatenated_arr)

# 60. Find the length of the longest string in a string array.
lengths = np.char.str_len(str_arr)
max_length = np.max(lengths)
print("\n60. Length of the longest string:\n", max_length)

56. Occurrences of substring 'o':
 [2 0 0]

57. Uppercase characters in each string:
 ['HW' 'NPIFUN' 'DS']
58. Replace spaces with underscores:
 ['Hello_World' 'NumPy_Is_FUN' 'Data_Science']

59. Concatenate '!!!' to each string:
 ['Hello World!!!' 'NumPy Is FUN!!!' 'Data Science!!!']

60. Length of the longest string:
 12


In [14]:

# 61. Generate 100 random integers (1–1000) and compute mean, median, variance, and std deviation.
data_100 = np.random.randint(1, 1001, size=100)
mean_61 = np.mean(data_100)
median_61 = np.median(data_100)
variance_61 = np.var(data_100)
std_dev_61 = np.std(data_100)
print("61. Stats for 100 random integers (1–1000):")
print("Mean:", mean_61)
print("Median:", median_61)
print("Variance:", variance_61)
print("Standard Deviation:", std_dev_61)

# 62. Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles.
data_50 = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(data_50, 25)
percentile_75 = np.percentile(data_50, 75)
print("\n62. Percentiles for 50 random numbers (1–100):")
print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)

# 63. Compute correlation coefficient between two arrays using np.corrcoef.
x = np.random.randint(10, 100, size=30)
y = np.random.randint(10, 100, size=30)
corr_matrix = np.corrcoef(x, y)
print("\n63. Correlation coefficient matrix:\n", corr_matrix)
print("Correlation between x and y:", corr_matrix[0, 1])

# 64. Perform matrix multiplication using np.dot.
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
dot_product = np.dot(A, B)
print("\n64. Matrix multiplication (A.dot(B)):\n", dot_product)

# 65. Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50 integers.
data_65 = np.random.randint(1, 201, size=50)
percentile_10 = np.percentile(data_65, 10)
percentile_50 = np.percentile(data_65, 50)
percentile_90 = np.percentile(data_65, 90)

q1 = np.percentile(data_65, 25)  # Q1
q2 = np.percentile(data_65, 50)  # Q2 (median)
q3 = np.percentile(data_65, 75)  # Q3

print("\n65. Percentiles and quartiles for 50 random integers (1–200):")
print("10th percentile:", percentile_10)
print("50th percentile (Median):", percentile_50)
print("90th percentile:", percentile_90)
print("Q1 (25%):", q1)
print("Q2 (50%):", q2)
print("Q3 (75%):", q3)


61. Stats for 100 random integers (1–1000):
Mean: 479.27
Median: 500.0
Variance: 82781.13709999999
Standard Deviation: 287.71711297731315

62. Percentiles for 50 random numbers (1–100):
25th percentile: 18.25
75th percentile: 75.0

63. Correlation coefficient matrix:
 [[1.00000000e+00 7.21286483e-05]
 [7.21286483e-05 1.00000000e+00]]
Correlation between x and y: 7.212864833323532e-05

64. Matrix multiplication (A.dot(B)):
 [[19 22]
 [43 50]]

65. Percentiles and quartiles for 50 random integers (1–200):
10th percentile: 22.200000000000003
50th percentile (Median): 93.0
90th percentile: 157.9
Q1 (25%): 57.5
Q2 (50%): 93.0
Q3 (75%): 126.5


In [15]:
arr = np.array([5, 22, 15, 33, 42, 7, 20, 35, 40, 10])

# 66. Find index of a specific element in an array.
index_66 = np.where(arr == 33)[0]
print("66. Index of element 33:\n", index_66)

# 67. Sort a random array in ascending order.
sorted_arr = np.sort(arr)
print("\n67. Sorted array in ascending order:\n", sorted_arr)

# 68. Filter elements greater than 20.
greater_than_20 = arr[arr > 20]
print("\n68. Elements greater than 20:\n", greater_than_20)

# 69. Filter elements divisible by 3.
divisible_by_3 = arr[arr % 3 == 0]
print("\n69. Elements divisible by 3:\n", divisible_by_3)

# 70. Filter elements between 20 and 40 (inclusive).
between_20_40 = arr[(arr >= 20) & (arr <= 40)]
print("\n70. Elements between 20 and 40 (inclusive):\n", between_20_40)

66. Index of element 33:
 [3]

67. Sorted array in ascending order:
 [ 5  7 10 15 20 22 33 35 40 42]

68. Elements greater than 20:
 [22 33 42 35 40]

69. Elements divisible by 3:
 [15 33 42]

70. Elements between 20 and 40 (inclusive):
 [22 33 20 35 40]


In [16]:
arr = np.array([1, 256, 1024], dtype=np.int32)

# 71. Check byte order of a NumPy array using dtype.byteorder
byte_order = arr.dtype.byteorder
# Interpreting the result
if byte_order == '=':
    byte_order_desc = "Native (depends on system: '<' for little-endian, '>' for big-endian)"
elif byte_order == '<':
    byte_order_desc = "Little-endian"
elif byte_order == '>':
    byte_order_desc = "Big-endian"
else:
    byte_order_desc = f"Unknown ({byte_order})"

print("71. Byte order of array:", byte_order)
print("Description:", byte_order_desc)

# 72. Perform in-place byte swapping using byteswap()
# Note: byteswap() by default returns a new array; to do it in-place, use `arr.byteswap(inplace=True)`
arr_swapped = arr.copy()
arr_swapped.byteswap(inplace=True)

print("\n72. Array after in-place byte swapping:\n", arr_swapped)

71. Byte order of array: =
Description: Native (depends on system: '<' for little-endian, '>' for big-endian)

72. Array after in-place byte swapping:
 [16777216    65536   262144]
